openapi: 3.0.0
info:
  title: "Tech Datamart Challenge API"
  description: An API to solve some challenges for Tech Datamart
  version: 1.0.0

paths:

  /:
    get:
      operationId: api.services.main.welcome
      tags:
        - home
      summary: Retrieves welcome message
      description: Displays welcome message
      responses:
        200:
          description: See a welcome message

  /health:
    get:
      operationId: api.services.main.health
      tags:
        - health
      summary: Retrieves health status of this application
      description: Perform health check on flask api
      responses:
        200:
          description: Application is functioning normally

  /merge_arrays:
      post:
        operationId: api.services.algorithms.merge_arrays_endpoint
        summary: Merge two lists and return a new ordered list.
        description: A function that use merge algorithm to merge two ordered lists.
        tags:
          - "ALGORITHMS"
        requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    list_1:
                      type: array
                      items:
                        type: integer
                    list_2:
                      type: array
                      items:
                        type: integer
                  required:
                    - list_1
                    - list_2

        responses:
          '200':    # status code
            description: A JSON with information about merge array endpoint result
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    sucess:
                      type: boolean
                      example: True
                    message:
                      type: string
                    mixed_ordered_list:
                      type: array
                      items:
                        type: integer
          '404':
            description: Not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Not found
          '406':
            description: Not acceptable
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Not acceptable
          '429':
            description: Too many requests
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Too many requests
          'default':
            description: Unexpected error
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    sucess:
                      type: boolean
                      example: True
                    error_message:
                      type: string
                      example: Unexpected error

  /median:
      post:
        operationId: api.services.algorithms.find_median_endpoint
        summary: An endpoint to get the median of a number set.
        description: The endpoint uses the **middle of the middle two** classic algorithm to calculate the median of a number set.
        tags:
          - "ALGORITHMS"
        requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    list:
                      type: array
                      items:
                        type: number
                  required:
                    - list

        responses:
          '200':    # status code
            description: A JSON with information about median of number set
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    sucess:
                      type: boolean
                      example: True
                    message:
                      type: string
                    median:
                      type: number
          '404':
            description: Not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Not found
          '406':
            description: Not acceptable
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Not acceptable
          '429':
            description: Too many requests
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Too many requests
          'default':
            description: Unexpected error
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    sucess:
                      type: boolean
                      example: True
                    error_message:
                      type: string
                      example: Unexpected error

  /remove_duplicates:
      post:
        operationId: api.services.algorithms.remove_duplicates_endpoint
        summary: An endpoint to remove duplicate data.
        description: Given a data set, the endpoint filters that data and returns a unique data set in that set.
        tags:
          - "ALGORITHMS"
        requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    list:
                      type: array
                  required:
                    - list

        responses:
          '200':    # status code
            description: A JSON with information about the new cleaner list.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    sucess:
                      type: boolean
                      example: True
                    message:
                      type: string
                    filtered_list:
                      type: array
          '404':
            description: Not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Not found
          '406':
            description: Not acceptable
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Not acceptable
          '429':
            description: Too many requests
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Too many requests
          'default':
            description: Unexpected error
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    sucess:
                      type: boolean
                      example: True
                    error_message:
                      type: string
                      example: Unexpected error

  /binary_search:
      post:
        operationId: api.services.algorithms.binary_search_endpoint
        summary: An endpoint to find an element in an ordered list.
        description: Given a data set, the endpoint use a binary search to find the provided element in the data set.
        tags:
          - "ALGORITHMS"
        requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    ordered_list:
                      type: array
                      items:
                        type: number
                    element:
                      type: number
                  required:
                    - ordered_list
                    - element

        responses:
          '200':    # status code
            description: A JSON with information about the new cleaner list.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    sucess:
                      type: boolean
                      example: True
                    message:
                      type: string
                    found::
                      type: boolean
          '404':
            description: Not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Not found
          '406':
            description: Not acceptable
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Not acceptable
          '429':
            description: Too many requests
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Too many requests
          'default':
            description: Unexpected error
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    sucess:
                      type: boolean
                      example: True
                    error_message:
                      type: string
                      example: Unexpected error
